services:
  # Backend FastAPI service
  - type: web
    name: pdf-rag-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /status/
